### ISSUE TITLE
Plugin does not make word clouds for my vault. 

### ISSUE THREAD

**Issue by wealthychef1** [joethei/obsidian-tagcloud#13]
From this code: 

````markdown
```wordcloud
```
````

I see this, which is very wrong, as I have over 5,000 notes.  Any words of advice?  Looks like the maintainer is on holiday for a bit, happy new years to all

<img width="412" alt="2023-01-12 22 55 21 CleanShot Obsidian" src="https://user-images.githubusercontent.com/4825448/212115631-bfce623e-c5ed-4cf6-8262-61f2de790ae2.png">

**Comment by elephino** [comment]
It seems like you have to add a maxDepth attribute to get additional words to show up. 50 worked for me to go from what you're seeing to a larger cloud. Unfortunately I seem to be plagued by the next issue down the line from the one you're having: I can't seem to get the stopwords I've added to my plugin preferences to be removed from the results, so the wordcloud is bigger, but still pretty un-enlightening. For reference, here are the attributes I've tried that have mostly worked:

```wordcloud
width: 640
height: 480
minFontSize: 14
maxDepth: 50
shrinkToFit: true
stopwords: true
```

And here's my list of stopwords I tried adding:
"uri"
the
be
to
of
and
a
in
that
have
I
it
for
not
on
with
he
as
you
do
at
this
but
his
by
from
they
we
say
her
she
or
an
will
my
one
all
would
there
their
what
so
up
out
if
about
who
get
which
go
me
when
make
can
like
time
no
just
him
know
take
people
into
year
your
good
some
could
them
see
other
than
then
now
look
only
come
its
over
think
also
back
after
use
two
how
our
work
first
well
way
even
new
want
because
any
these
give
day
most
us

Hope my solution helps and that you have better luck than me once you're past your current issue.

**Comment by elephino** [comment]
I apologize for the length of that list, by the way. I wanted to provide all information as it's supposed to show up in the plugin's preferences instead of providing a comma-separated list of stopwords and risk being misinterpreted as having entered the data in a particularly incorrect manner.

**Comment by wealthychef1** [comment]
Thanks, as is, I'd say the plugin is unusable.  Would be cool if there were a working version of this somewhere!  I'll keep my eye out to see if things get better.  Thanks for your help.

**Comment by joethei** [comment]
There was an issue where stopwords were not properly removed.
This has now been fixed.

Sorry about that.
